spring:
  h2:
    console:
      enabled: false
    datasource:
      url: jdbc:h2:mem:skaptobet;DATABASE_TO_UPPER=false
      username: sa
      password: password
      driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    defer-datasource-initialization: true
